# Generated by Django 4.2.7 on 2023-11-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTratamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('microchip', models.CharField(max_length=50)),
                ('fecha_atencion', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoVetMartin.tratamiento')),
            ],
        ),
    ]
